version: 2.1

jobs:
  build:
    docker:
      - image: golang:1.21
    steps:
      - checkout
      - run: echo 'export VERSION=$(git describe --tags --always --dirty="-dev")' >> $BASH_ENV
      - run: source $BASH_ENV
      - run: GOOS=linux GOARCH=amd64 go build -o wpnix main.go  
      - run: chmod +x wpnix
      - run: mkdir build
      - run: |
          mkdir -p wpnix-${VERSION}/DEBIAN
          echo "Package: wpnix" > wpnix-${VERSION}/DEBIAN/control
          echo "Version: 1.0.0" >> wpnix-${VERSION}/DEBIAN/control
          echo "Section: web" >> wpnix-${VERSION}/DEBIAN/control
          echo "Priority: optional" >> wpnix-${VERSION}/DEBIAN/control
          echo "Architecture: amd64" >> wpnix-${VERSION}/DEBIAN/control
          echo "Depends: nginx, php8.2, php8.2-fpm, php8.2-mysql, php8.2-xml, php8.2-mbstring, php8.2-curl, php8.2-zip, perl, certbot" >> wpnix-${VERSION}/DEBIAN/control
          echo "Maintainer: Your Name <youremail@example.com>" >> wpnix-${VERSION}/DEBIAN/control
          echo "Description: Installs WordPress and sets up an Nginx server block." >> wpnix-${VERSION}/DEBIAN/control
          mkdir -p wpnix-${VERSION}/usr/local/bin
          cp wpnix wpnix-${VERSION}/usr/local/bin/wpnix
          dpkg-deb --build wpnix-${VERSION}
      - run: gem install package_cloud
      - run: package_cloud push carlHandy/wpnix/os/version ./build/wpnix_${VERSION}_amd64.deb

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
