version: 2.1

jobs:
  build:
    docker:
      - image: golang:1.21
    steps:
      - checkout
      - run: GOOS=linux GOARCH=amd64 go build -o wpnix 
      - run: chmod +x wpnix
      - run: mkdir build
      - run: |
          mkdir -p build/wpnix_${CIRCLE_BUILD_NUM}/DEBIAN
          # echo "CircleCI Build Number: ${CIRCLE_BUILD_NUM}" > build/wpnix_${CIRCLE_BUILD_NUM}/DEBIAN/postinst
          # echo "This package was built by CircleCI in build #${CIRCLE_BUILD_NUM}." >> build/wpnix_${CIRCLE_BUILD_NUM}/DEBIAN/postinst
          # chmod +x build/wpnix_${CIRCLE_BUILD_NUM}/DEBIAN/postinst
          echo "Package: wpnix" > build/wpnix_${CIRCLE_BUILD_NUM}/DEBIAN/control
          echo "Version: ${CIRCLE_BUILD_NUM}" >> build/wpnix_${CIRCLE_BUILD_NUM}/DEBIAN/control
          echo "Section: web" >> build/wpnix_${CIRCLE_BUILD_NUM}/DEBIAN/control
          echo "Priority: optional" >> build/wpnix_${CIRCLE_BUILD_NUM}/DEBIAN/control
          echo "Architecture: amd64" >> build/wpnix_${CIRCLE_BUILD_NUM}/DEBIAN/control
          echo "Depends: nginx, php8.2, php8.2-fpm, php8.2-mysql, php8.2-xml, php8.2-mbstring, php8.2-curl, php8.2-zip, perl, certbot" >> build/wpnix_${CIRCLE_BUILD_NUM}/DEBIAN/control
          echo "Maintainer: Carl Handy carl@handy.gy" >> build/wpnix_${CIRCLE_BUILD_NUM}/DEBIAN/control
          echo "Description: Installs WordPress and sets up an Nginx server block." >> build/wpnix_${CIRCLE_BUILD_NUM}/DEBIAN/control
          mkdir -p build/wpnix_${CIRCLE_BUILD_NUM}/usr/local/bin
          cp wpnix build/wpnix_${CIRCLE_BUILD_NUM}/usr/local/bin/wpnix
          dpkg-deb --build build/wpnix_${CIRCLE_BUILD_NUM}
      - run: apt-get update && apt-get install -y ruby-full && gem install package_cloud
      - run: |
          package_cloud push carlHandy/wpnix/any/any build/wpnix_${CIRCLE_BUILD_NUM}.deb

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
