version: 2.1

jobs:
  build:
    docker:
      - image: golang:1.21
    steps:
      - checkout
      - run: GOOS=linux GOARCH=amd64 go build -o wpnix main.go  
      - run: chmod +x wpnix
      - run: mkdir build
      - run: |
          VERSION=$(git describe --tags --always)
          VERSION_NUMBER=$(echo $VERSION | awk -F. '{print $1"."$2"."$3+1}')
          mkdir -p build/wpnix_${VERSION_NUMBER}/DEBIAN
          echo "Package: wpnix" > build/wpnix_${VERSION_NUMBER}/DEBIAN/control
          echo "Version: ${VERSION_NUMBER%.*}.`echo $VERSION_NUMBER | awk -F. '{print $3+1}'`" >> build/wpnix_${VERSION_NUMBER}/DEBIAN/control
          echo "Section: web" >> build/wpnix_${VERSION_NUMBER}/DEBIAN/control
          echo "Priority: optional" >> build/wpnix_${VERSION_NUMBER}/DEBIAN/control
          echo "Architecture: amd64" >> build/wpnix_${VERSION_NUMBER}/DEBIAN/control
          echo "Depends: nginx, php8.2, php8.2-fpm, php8.2-mysql, php8.2-xml, php8.2-mbstring, php8.2-curl, php8.2-zip, perl, certbot" >> build/wpnix_${VERSION_NUMBER}/DEBIAN/control
          echo "Maintainer: Carl Handy carl@handy.gy" >> build/wpnix_${VERSION_NUMBER}/DEBIAN/control
          echo "Description: Installs WordPress and sets up an Nginx server block." >> build/wpnix_${VERSION_NUMBER}/DEBIAN/control
          mkdir -p build/wpnix_${VERSION_NUMBER}/usr/local/bin
          cp wpnix build/wpnix_${VERSION_NUMBER}/usr/local/bin/wpnix
          dpkg-deb --build build/wpnix_${VERSION_NUMBER}
      - run: apt-get update && apt-get install -y ruby-full && gem install package_cloud
      - run: |
          VERSION=$(git describe --tags --always)
          VERSION_NUMBER=$(echo $VERSION | awk -F. '{print $1"."$2"."$3+1}')
          package_cloud push carlHandy/wpnix/any/any build/wpnix_${VERSION_NUMBER}.deb

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
