version: 2.1

jobs:
  build:
    docker:
      - image: golang:1.21
    steps:
      - checkout
      - run: GOOS=linux GOARCH=amd64 go build -o wpnix main.go  
      - run: chmod +x wpnix
      - run: mkdir build
      - run: |
          mkdir -p build/wpnix/DEBIAN
          echo "Package: wpnix" > build/wpnix/DEBIAN/control
          echo "Version: 1.0.0" >> build/wpnix/DEBIAN/control
          echo "Section: web" >> build/wpnix/DEBIAN/control
          echo "Priority: optional" >> build/wpnix/DEBIAN/control
          echo "Architecture: amd64" >> build/wpnix/DEBIAN/control
          echo "Depends: nginx, php8.2, php8.2-fpm, php8.2-mysql, php8.2-xml, php8.2-mbstring, php8.2-curl, php8.2-zip, perl, certbot" >> build/wpnix/DEBIAN/control
          echo "Maintainer: Carl Handy carl@handy.gy" >> build/wpnix/DEBIAN/control
          echo "Description: Installs WordPress and sets up an Nginx server block." >> build/wpnix/DEBIAN/control
          mkdir -p build/wpnix/usr/local/bin
          cp wpnix build/wpnix/usr/local/bin/wpnix
          dpkg-deb --build build/wpnix
      - run: apt-get update && apt-get install -y ruby-full && gem install package_cloud
      - run: package_cloud push carlHandy/wpnix/any/any build/wpnix.deb

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
